---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhang.
--- DateTime: 2026/3/13 16:16
---- 参数列表
---- KEYS[1]: stockKey (库存Key)
---- KEYS[2]: orderKey (订单Key)
---- ARGV[1]: userId   (用户ID)
--- 1.判断库存是否充足
local stock = redis.call('get', KEYS[1])
if(not stock or tonumber(stock) <= 0) then
    --- 库存不足
    return 1
end
--- 2.判断用户是否下单
if (redis.call('sismember', KEYS[2], ARGV[1]) == 1) then
    --- 存在，说明是重复下单，返回2
    return 2
end
--- 3.扣库存
redis.call("incrby", KEYS[1], -1)
--- 4.下单
redis.call("sadd", KEYS[2], ARGV[1])